### ISSUE TITLE
Can't use include_blank: false for required inputs, but you can set prompt: ''

### ISSUE THREAD

**Issue by vincentwoo** [formtastic/formtastic#1285] opened 2019-10-18 22:00 UTC
I have a select that looks like

```ruby
<%= f.input :language, collection: values, include_blank: false %>
```

The object always has `language` set to a value in `values`, so I don't want to show the blank field. Recently we made this field required, which broke this code. I was unable to get the previous behavior *except* by doing this, which feels like a hack:

```ruby
<%= f.input :language, collection: values, prompt: '' %>
```

Is this by design? Am I missing something?

**Comment by justinfrench** [comment] 2020-06-21 05:54
@vincentwoo the `include_blank` specs asserts that there should be no blank field if you use `include_blank: false`. So the issue you're having is not by design. However, I can't readily see any issues in the code — we don't change our logic based on whether the field is required or not. My best guess is that we might have some flawed interplay of logic between `include_blank` and `prompt`, but your example code above isn't indicating that.

Are you able to provide a bit more sample code (which you tried to use, what you expected in the output, what you got)?

I'm closing for now (since it's 6 months old), but please do re-open if you're still having issues and can help isolate this.

**Closed by justinfrench** 2020-06-21 05:54 UTC

**Comment by vincentwoo** [comment] 2020-06-21 09:41
I believe this issue comes down to whether the field is required. Here is simpler sample code that should help you reproduce.

```ruby
<%= f.input :language,
  collection: { a: 'a', b: 'b' },
  required: true,
  selected: 'b',
  prompt: ''
%>
```
(correctly) renders as

```html
<li class="select input required" id="question_language_input">
  <label for="question_language" class="">Language</label>
  <select name="question[language]" id="question_language" required="required" class="form-control">
    <option value="a">a</option>
    <option selected="selected" value="b">b</option>
  </select>
</li>
```

However, if you instead attempt to achieve no blank prompt via:

```ruby
<%= f.input :language,
  collection: { a: 'a', b: 'b' },
  required: true,
  selected: 'b',
  include_blank: false
%>
```

formtastic errors out with `include_blank cannot be false for a required field.`

This does not seem intentional to me.

**Comment by vincentwoo** [comment] 2020-06-21 09:47
I see upon additional research that this is related to actionview throwing the afforementioned error: https://github.com/rails/rails/pull/20124. I'm unsure where formtastic should land on this - it seems odd to have to do this workaround.

**Comment by justinfrench** [comment] 2020-06-24 02:14
@vincentwoo thanks for digging into this a bit further. It sounds like this is a Rails issue more than a Formtastic issue.

If I understand the situation correctly, you have a required field, but you want to omit the "blank" option because you've pre-selected a good default option in the model instance. This does seem like a bit of an edge case, and I'm not sure if there's a way Formtastic could or should work around it, given it's core Rails logic that seems reasonable.
