### ISSUE TITLE
Field flattens array from DB

### ISSUE THREAD

**Issue by rhulse** [formtastic/formtastic#1144] opened 2015-03-24 23:05 UTC
I just upgraded to Formtastic to version 3 from V 2.

 I have a model that has tags on it (acts as taggable on). To edit these in a form I have .tag_list on the model.

When I use tag_list as a field name it flattens the array and puts spaces between the values.

In version 2 in put a comma seperated list in the values.

To temporarily fix this I am doing this:

```
def tag_field(form, field, data, title=nil)
    values = form.object.send(field).join(',')
    form.input field, input_html: {value: values, autocomplete: 'off'}, wrapper_html: {'data-tags' => data}, label: title
end
```

**Comment by justinfrench** [comment] 2015-03-25 03:10
I'm confused. Can you show me what you were trying to do with standard Formtastic methods, what the relevant HTML output was, and what output you expected?

It sounds like `.tag_list` isn't an array or other collection that Formtastic is expecting, or you're doing something very strange. What does `.tag_list.inspect` look like?

**Comment by rhulse** [comment] 2015-03-25 06:22
~/Sites/elf (development) > a.tag_list.inspect
    => "[\"Cricket World Cup\", \"Christchurch rates\"]"

If I do this in the form:

      <%= form.input :tag_list %>
 
I get this in the field:

    Cricket World Cup Christchurch rates

Rolling back to Formtastic v2 I get this, same form code:

    Cricket World Cup, Christchurch rates

The helper in the previous comment was just to DRY up the code; it would look like this in the form directly:

    form.input :tag_list, input_html: {autocomplete: 'off'}, wrapper_html: {'data-tags' => data}, label: title

No commas to be seen with this either.

**Comment by felipeclopes** [comment] 2015-11-09 02:20
+1

**Comment by justinfrench** [comment] 2015-11-09 02:45
@rhulse @felipeclopes 

If I follow the method chain, let's see if we can figure this out. Let's start here;

`form.input :tag_list, input_html: {autocomplete: 'off'}, wrapper_html: {'data-tags' => data}, label: title`

I presume this ends up calling StringInput, though it's not explicit in your example and not 100% clear to me. Let's assume it does, as you seem to want a text field. This ultimately calls `StringInput`, which hands off most of the heavy lifting to `Stringish`

```
        def to_html
          input_wrapping do
            label_html <<
            builder.text_field(method, input_html_options)
          end
        end
```

As you can see, it calls out to the Rails form builder's `text_field` helper. `input_html_options` doesn't do anything to transform your value either:

```
        def input_html_options
          {
            :id => dom_id,
            :required => required_attribute?,
            :autofocus => autofocus?,
            :readonly => readonly?
          }.merge(options[:input_html] || {})
        end
```

So, my _guess_ is that while you upgraded Formtastic, you also upgraded Rails, and that something in Rails has changed in the way `text_field` handles this scenario. Can confirm if you upgraded Formtastic in isolation, or if other gems (like Rails or ActiveAdmin) were involved?

I _think_ the fix for this is to create a `tag_list_as_striing` accessor on your model and use that in the form, so that you have control over exactly how the tag list is transformed back and forth without fighting against Rails. I can help you with that after we can confirm if this is isolated to Rails or not.

**Comment by justinfrench** [comment] 2016-03-26 21:54
Closing due to lack of activity. Please feel free to re-open with new information!

**Comment by joker-777** [comment] 2016-04-17 10:41
:+1: I have the same problem

**Comment by joker-777** [comment] 2016-04-17 12:57
Hi, it seem like Rails behavior changed and it displays now an array separated with spaces. @justinfrench Is there a way of defining a proc in the `input` definition which transforms the value? There used to be `value_method` but I think it was removed.
Creating this `accessor` like you already suggested is a solution but then you also have to write 'setter' method which we don't need here. We just need to transform the value into something else. The rest is handled by rails properly.

**Comment by gingerlime** [comment] 2016-04-17 16:14
How about this as a workaround?

```ruby
form.input :tag_list, :input_html => {:value => f.object.tag_list.join(',')}
```

**Comment by gingerlime** [comment] 2016-04-17 18:38
I think [this acts_as_taggable_on wiki page](https://github.com/mbleigh/acts-as-taggable-on/wiki/Add-a-tag-field-to-forms-in-Rails--4.2-and-above) confirms this is a rails change rather than something specific to formtastic.

**Comment by justinfrench** [comment] 2016-04-17 20:50
@hingerlime does that work-around _work_ for now?

**Comment by gingerlime** [comment] 2016-04-17 21:03
I tested very quickly, but as far as I can tell, yes. It does work. I'm working together with @joker-777 so I'll wait for him to confirm, since he's been working on this bug on our end.

**Comment by joker-777** [comment] 2016-04-18 09:14
Yes, it works perfectly. Thanks @gingerlime

**Comment by justinfrench** [comment] 2016-04-18 09:34
Ok great! I'm going to leave this open for now. Would be good if someone could explore a patch that detects the acts_as_taggable column and automatically applies the work-around.

**Comment by gingerlime** [comment] 2016-04-18 09:45
I'm not that familiar with formtastic, but should be fairly straight-forward to detect if the field is mounted by acts_as_taggable_on and apply this (as an aside, it's not usually an actual column, but an external model, which acts_as_taggable_on gem handles for you...).

I think it would be nice feature for acts_as_taggable_on / formtastic users, but this implicit workaround (especially now going against the rails defaults) might be confusing if you don't expect it? Not sure what's the formtastic "philosophy" for doing things automatically this way.

**Comment by mikz** [comment] 2016-04-18 10:02
We could try to do something. Could you create a sample project reproducing the issue including a failing test case? That would help tremendously.

**Comment by joker-777** [comment] 2016-04-20 08:09
I wouldn't implement something which detects `acts_as_taggable_on` and applies a workaround at all. I think a good help page in the wiki which explains the problem and offers this solution would be totally enough.

**Closed** 2020-06-21 05:23 UTC
Labels: bug
